name: Template - Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        description: "The name of the image (e.g., high-flyers/ros-core)"
        required: true
        type: string
      dockerfile_path:
        description: "Path to the Dockerfile"
        required: true
        type: string
      base_tag:
        description: "The base tag for the image (e.g., latest)"
        required: false
        type: string
        default: latest
      amd64_build:
        description: "Build for linux/amd64"
        required: false
        type: boolean
        default: true
      arm64_build:
        description: "Build for linux/arm64"
        required: false
        type: boolean
        default: true
      build_args:
        description: "List of build-args (e.g. ROS_CORE_TAG=humble)"
        required: false
        type: string
        default: ""

env:
  REGISTRY: ghcr.io

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux/amd64
            arch: amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            arch: arm64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        if: ${{ (matrix.arch == 'amd64' && inputs.amd64_build) || (matrix.arch == 'arm64' && inputs.arm64_build) }}
        uses: actions/checkout@v4

      - name: Log in to GHCR
        if: ${{ (matrix.arch == 'amd64' && inputs.amd64_build) || (matrix.arch == 'arm64' && inputs.arm64_build) }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set PR Tag Suffix
        if: ${{ (matrix.arch == 'amd64' && inputs.amd64_build) || (matrix.arch == 'arm64' && inputs.arm64_build) }}
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH_NAME="${{ github.head_ref }}"
            SAFE_BRANCH=$(echo "$BRANCH_NAME" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
            echo "SUFFIX=-$SAFE_BRANCH" >> $GITHUB_OUTPUT
          else
            echo "SUFFIX=" >> $GITHUB_OUTPUT
          fi

      - name: Build and push image
        if: ${{ (matrix.arch == 'amd64' && inputs.amd64_build) || (matrix.arch == 'arm64' && inputs.arm64_build) }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          push: true
          platforms: ${{ matrix.platform }}
          build-args: ${{ inputs.build_args }}
          tags: |
            ${{ env.REGISTRY }}/${{ inputs.image_name }}:${{ inputs.base_tag }}-${{ matrix.arch }}${{ steps.vars.outputs.SUFFIX }}

  manifest:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && inputs.amd64_build && inputs.arm64_build
    permissions:
      packages: write
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create \
            -t ${{ env.REGISTRY }}/${{ inputs.image_name }}:${{ inputs.base_tag }} \
            ${{ env.REGISTRY }}/${{ inputs.image_name }}:${{ inputs.base_tag }}-amd64 \
            ${{ env.REGISTRY }}/${{ inputs.image_name }}:${{ inputs.base_tag }}-arm64
