name: Build and Push Docker Image (native amd64 & arm64)

on:
  push:
    branches: ["main", "workflow"]
  pull_request:

jobs:
  docker-distros:
    strategy:
      matrix:
        ros_distro: [humble, jazzy]
    uses: ./github/workflows/docker-template.yaml
    with:
      image_name: high-flyers/ros-core
      dockerfile_path: ./images/ros-core-${{ matrix.ros_distro }}.Dockerfile
      base_tag: ${{ matrix.ros_distro }}
    secrets: inherit
    
  docker-latest:
    uses: ./.github/workflows/docker-template.yaml
    with:
      image_name: high-flyers/ros-core
      dockerfile_path: ./images/ros-core-humble.Dockerfile
      base_tag: latest
    secrets: inherit
